version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.9-gatsby
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${MANAG_API_SECRET}
        port: 8090
        databases:
          default:
            connector: postgres
            host: db
            port: 5432
            user: ${DB_POSTGRES_USER}
            password: ${DB_POSTGRES_PASSWORD}
            connectionLimit: 2
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USER}
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080  
